[project]
name = "mai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiocache[redis]>=0.12.3",
    "aiohttp>=3.13.3",
    "asyncpg>=0.31.0",
    "click>=8.3.1",
    "humanize>=4.15.0",
    "jishaku>=2.6.3",
    "loguru>=0.7.3",
    "psutil>=7.2.1",
    "pycordutils>=0.0.2",
    "pyshorteners>=1.0.1",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
    "sympy>=1.14.0",
    "watchfiles>=1.1.1",
    "discord-py",
]

[tool.uv.sources]
discord-py = { git = "https://github.com/Rapptz/discord.py.git" }
