FROM node:17.6.0

WORKDIR /usr/src/mai-frontend

ENV PATH /usr/src/mai-frontend/node_modules/.bin:$PATH

COPY package.json /usr/src/mai-frontend/package.json

RUN yarn install

COPY . .

CMD ["yarn", "start"]
